config/urls.py
from django.contrib import admin
from django.urls import path, include

from config.views import (
    TaskListView,
    TaskCreateView,
    update_status_view,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskUpdateView,
    TasklDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-view"),
    path("create_task/", TaskCreateView.as_view(), name="create-task"),
    path("update_task/<int:pk>", TaskUpdateView.as_view(), name="update-task"),
    path(
        "delete-task/<int:pk>",
        TasklDeleteView.as_view(),
        name="delete-task"
    ),


    path("tag_list/", TagListView.as_view(), name="tag-list"),
    path("tag_create/",
         TagCreateView.as_view(),
         name="tag-create"
         ),
    path("tag_update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tag_delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),

    path(
        "<int:pk>/update-status/",
        update_status_view,
        name="task-status-update"
    ),
]

app_name = "config"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("config.urls", namespace="config"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=55)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("status", "-created_at")

    def __str__(self) -> str:
        return self.content

config/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from config.models import Task, Tag


# Create your views here.

class TaskListView(generic.ListView):
    model = Task
    fields = "__all__"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    template_name = "config/task_form.html"
    success_url = reverse_lazy("config:task-view")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("config:task-view")


class TasklDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    template_name = "config/task_confirm_delete.html"
    success_url = reverse_lazy("config:task-view")


class TagListView(generic.ListView):
    model = Tag
    field = "__all__"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("config:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("config:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    template_name = "config/tag_confirm_delete.html"
    success_url = reverse_lazy("config:tag-list")


def update_status_view(request, pk):
    task = Task.objects.get(id=pk)
    task.status = not task.status
    task.save()

    return HttpResponseRedirect(reverse("config:task-view"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TodoList</title>
    <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous">
</head>
<body>
  <div class="container-fluid">
      <div class="row">
          <div class="col-sm-2" style="padding-top: 20px">
              {% block sidebar %}
                  {% include "includes/sidebar.html" %}
              {% endblock %}
          </div>
          <div class="col-sm-10 ">
              {% block content %}{% endblock %}
          </div>
      </div>
  </div>
</body>
</html>

templates/config/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="margin: 20px;">
    <h1 style="margin-bottom: 20px;">Are you sure you want to remove the tag <em>{{ tag.name }}</em>?</h1>
    <form action="" method="post" style="display: inline-block;">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px;">
    </form>
    <a href="{% url 'config:tag-list' %}" class="btn btn-secondary" style="display: inline-block;">Cancel</a>
  </div>
{% endblock %}

templates/config/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters%}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form| crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/config/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1 style="margin-top: 20px; display: inline-block;">Tags</h1>
  <a href="{% url 'config:tag-create' %}" style="float: right; margin-top: 20px;" class="btn btn-primary">Add</a>
{% if tag_list %}
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url 'config:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a></td>
          <td><a href="{% url 'config:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <h1>You have no tags!</h1>
{% endif %}
{% endblock %}

templates/config/tag_update.html
{% extends 'base.html'%}
{% load crispy_forms_filters %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <input class="btn btn-success" type="submit" value="Submit">
  </form>
{% endblock %}

templates/config/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div style="margin: 20px;">
    <h1 style="margin-bottom: 20px;">Are you sure you want to remove the content <em>{{ task.content }}</em>?</h1>
    <form action="" method="post" style="display: inline-block;">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Yes" class="btn btn-danger" style="margin-right: 10px;">
    </form>
    <a href="{% url 'config:task-view' %}" class="btn btn-secondary" style="display: inline-block;">Cancel</a>
  </div>
{% endblock %}

templates/config/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters%}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form| crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/config/task_list.html
{% extends "base.html" %}

{% block content %}
      <h1 style="padding-top: 20px">
        TODO list
        <a href="{% url 'config:create-task' %}" style="float: right" class="btn btn-primary">
          Add task
        </a>
      </h1>
    {% if task_list %}
      {% for task in task_list %}
          <li class="card mb-3">
              <div class="card-body">
                <h5 class="card-title">
                  <b>{{ task.content }}
                    {% if task.status %}
                      <span style="color: green;">Done</span>
                    {% else %} <span style="color: red;">Not done</span>
                    {% endif %}
                  </b>
                </h5>
                  <p class="card-text" style="color:#666666">
                    Created: {{ task.created_at }}
                    Deadline: {% if task.deadline %} {{ task.deadline }} {% endif %}
                  </p>
                  <p class="card-text" style="color:#999999">
                    Tags: {{ task.tags.all|join:", " }}
                    <a href="{% url 'config:update-task' pk=task.id %}">Update</a>
                    <a href="{% url 'config:delete-task' pk=task.id %}">Delete</a>
                    {% if task.status %}
                      <a href="{% url 'config:task-status-update' pk=task.id %}" class="btn btn-secondary float-right">Undo</a>
                    {% else %}
                      <a href="{% url 'config:task-status-update' pk=task.id %}" class="btn btn-success float-right">Complete</a>
                    {% endif %}
                  </p>
              </div>
          </li>
      {% endfor %}
    {% endif %}
{% endblock %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'config:task-view' %}">Home</a></li>
  <li class="list-group-item"><a href={% url 'config:tag-list' %}>Tags</a></li>
</ul>